# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import time
from tkinter import Tk, Canvas, Entry, Button, PhotoImage
from pathlib import Path
import os
from pygame import mixer

mixer.init()

username = None
password = None

current_dir = Path(os.path.dirname(os.path.abspath(__file__)))
ASSETS_PATH = current_dir / "assets"

MOVE_SOUND = os.path.join(current_dir, "assets", "move.wav")
SELECT_SOUND = os.path.join(current_dir, "assets", "select.wav")
SUCCESS_SOUND = os.path.join(current_dir, "assets", "success.wav")
FAIL_SOUND = os.path.join(current_dir, "assets", "fail.wav")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def on_enter_button_1(e):
    button_1.config(image=button_image_1_hover)  # Change to hover image
    canvas.itemconfig(image_6, state="normal")  # Show image_6
    mixer.Sound(MOVE_SOUND).play()  # Play move sound

def on_leave_button_1(e):
    button_1.config(image=button_image_1)  # Change back to the original image
    canvas.itemconfig(image_6, state="hidden")  # Hide image_6

def on_enter_button_2(e):
    button_2.config(image=button_image_2_hover)  # Change to hover image
    canvas.itemconfig(image_5, state="normal")  # Show image_5
    mixer.Sound(MOVE_SOUND).play()  # Play move sound

def on_leave_button_2(e):
    button_2.config(image=button_image_2)  # Change back to the original image
    canvas.itemconfig(image_5, state="hidden")  # Hide image_5

def clear_entries():
    # Clear username and password entries
    entry_1.delete(0, 'end')
    entry_2.delete(0, 'end')

    # Set focus to the root window to un-select all widgets
    window.focus_set()

def button_clicked(button):
    def delay_and_play_sound():
        mixer.Sound(SELECT_SOUND).play()  # Play select sound
        button.config(state="disabled")  # Disable the button temporarily to prevent rapid clicks
        time.sleep(1)  # Wait for 1 second
        button.config(state="normal")  # Re-enable the button

        # Check if the button is the login button
        if button == button_2:
            # Retrieve username and password from entry fields
            username_ = entry_1.get()
            password_ = entry_2.get()
            if username_ == "rfrx" and password_ == "123":
                print("success")
                mixer.Sound(SUCCESS_SOUND).play()
            else:
                print("fail")
                mixer.Sound(FAIL_SOUND).play()
                time.sleep(2)
                clear_entries()

    window.after_idle(delay_and_play_sound)  # Schedule the delay_and_play_sound function to run after idle

def center_window(window):
    window.update_idletasks()
    width = window.winfo_width()
    height = window.winfo_height()
    x = (window.winfo_screenwidth() // 2) - (width // 2)
    y = (window.winfo_screenheight() // 2) - (height // 2)
    window.geometry(f"{width}x{height}+{x}+{y}")

window = Tk()
window.title("Login")
window.geometry("500x350")  # Initial size of the window
window.configure(bg="#000000")
center_window(window)  # Center the window on the screen

canvas = Canvas(
    window,
    bg="#000000",
    height=350,
    width=500,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)
canvas.place(x=0, y=0)

entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    129.5,
    77.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=23.0,
    y=63.0,
    width=213.0,
    height=27.0
)
username = str(entry_1.get())


entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    129.5,
    156.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show="*"
)
entry_2.place(
    x=23.0,
    y=142.0,
    width=213.0,
    height=27.0
)

password = str(entry_2.get())

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_image_1_hover = PhotoImage(file=relative_to_assets("button_1(hover).png"))



button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: button_clicked(button_1),
    relief="flat",
    activebackground="#000000", 
)

button_1.place(x=65.0, y=260.0, width=160.3, height=36.0)
button_1.bind("<Enter>", on_enter_button_1)
button_1.bind("<Leave>", on_leave_button_1)



button_image_2 = PhotoImage(file=relative_to_assets("button_2.png"))
button_image_2_hover = PhotoImage(file=relative_to_assets("button_2(hover).png"))



button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: button_clicked(button_2),
    relief="flat",
    activebackground="#000000", 
)



button_2.place(x=65.0, y=215.0, width=100.4530258178711, height=36.49)
button_2.bind("<Enter>", on_enter_button_2)
button_2.bind("<Leave>", on_leave_button_2)



image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    413.0,
    167.0,
    image=image_image_1
)

image_image_2 = PhotoImage(file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    89.0,
    125.0,
    image=image_image_2
)

image_image_3 = PhotoImage(file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    91.0,
    46.0,
    image=image_image_3
)



image_image_4 = PhotoImage(file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    343.0,
    167.0,
    image=image_image_4
)

image_image_5 = PhotoImage(file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    40.0,
    232.0,
    image=image_image_5,
    state="hidden"  # Initially hide image_5
)

image_image_6 = PhotoImage(file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    40.0,
    277.0,
    image=image_image_6,
    state="hidden"  # Initially hide image_6
)

window.resizable(False, False)
window.mainloop()
